# coding: utf-8

"""
    Python client for Payment Initiation API

    Based on https://github.com/OpenBankingUK/payment-initiation-api-spec

    OpenAPI spec version: v1.1.1
    Spec: https://www.openbanking.org.uk/read-write-apis/
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import openbanking_payment_client
from api.payments_api import PaymentsApi  # noqa: E501
from openbanking_payment_client.rest import ApiException


class TestPaymentsApi(unittest.TestCase):
    """PaymentsApi unit test stubs"""

    def setUp(self):
        self.api = api.payments_api.PaymentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_payment_submission(self):
        """Test case for create_payment_submission

        Create a payment submission  # noqa: E501
        """
        pass

    def test_create_single_immediate_payment(self):
        """Test case for create_single_immediate_payment

        Create a single immediate payment  # noqa: E501
        """
        pass

    def test_get_payment_submission(self):
        """Test case for get_payment_submission

        Get a payment submission  # noqa: E501
        """
        pass

    def test_get_single_immediate_payment(self):
        """Test case for get_single_immediate_payment

        Get a single immediate payment  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
