# coding: utf-8

"""
    Python client for Payment Initiation API

    Based on https://github.com/OpenBankingUK/payment-initiation-api-spec

    OpenAPI spec version: v1.1.1
    Spec: https://www.openbanking.org.uk/read-write-apis/
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from openbanking_payment_client.model.payment_submission import PaymentSubmission  # noqa: F401,E501
from openbanking_payment_client.model.risk import Risk  # noqa: F401,E501


class PaymentSubmissionPOSTRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'data': 'PaymentSubmission',
        'risk': 'Risk'
    }

    attribute_map = {
        'data': 'Data',
        'risk': 'Risk'
    }

    def __init__(self, data=None, risk=None):  # noqa: E501
        """PaymentSubmissionPOSTRequest - a model defined in Swagger"""  # noqa: E501

        self._data = None
        self._risk = None
        self.discriminator = None

        self.data = data
        self.risk = risk

    @property
    def data(self):
        """Gets the data of this PaymentSubmissionPOSTRequest.  # noqa: E501


        :return: The data of this PaymentSubmissionPOSTRequest.  # noqa: E501
        :rtype: PaymentSubmission
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this PaymentSubmissionPOSTRequest.


        :param data: The data of this PaymentSubmissionPOSTRequest.  # noqa: E501
        :type: PaymentSubmission
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")  # noqa: E501

        self._data = data

    @property
    def risk(self):
        """Gets the risk of this PaymentSubmissionPOSTRequest.  # noqa: E501


        :return: The risk of this PaymentSubmissionPOSTRequest.  # noqa: E501
        :rtype: Risk
        """
        return self._risk

    @risk.setter
    def risk(self, risk):
        """Sets the risk of this PaymentSubmissionPOSTRequest.


        :param risk: The risk of this PaymentSubmissionPOSTRequest.  # noqa: E501
        :type: Risk
        """
        if risk is None:
            raise ValueError("Invalid value for `risk`, must not be `None`")  # noqa: E501

        self._risk = risk

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PaymentSubmissionPOSTRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
