# coding: utf-8

"""
    Python client for Payment Initiation API

    Based on https://github.com/OpenBankingUK/payment-initiation-api-spec

    OpenAPI spec version: v1.1.1
    Spec: https://www.openbanking.org.uk/read-write-apis/
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class RiskDeliveryAddress(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'address_line': 'list[str]',
        'street_name': 'str',
        'building_number': 'str',
        'post_code': 'str',
        'town_name': 'str',
        'country_sub_division': 'list[str]',
        'country': 'str'
    }

    attribute_map = {
        'address_line': 'AddressLine',
        'street_name': 'StreetName',
        'building_number': 'BuildingNumber',
        'post_code': 'PostCode',
        'town_name': 'TownName',
        'country_sub_division': 'CountrySubDivision',
        'country': 'Country'
    }

    def __init__(self, address_line=None, street_name=None, building_number=None, post_code=None, town_name=None, country_sub_division=None, country=None):  # noqa: E501
        """RiskDeliveryAddress - a model defined in Swagger"""  # noqa: E501

        self._address_line = None
        self._street_name = None
        self._building_number = None
        self._post_code = None
        self._town_name = None
        self._country_sub_division = None
        self._country = None
        self.discriminator = None

        if address_line is not None:
            self.address_line = address_line
        if street_name is not None:
            self.street_name = street_name
        if building_number is not None:
            self.building_number = building_number
        if post_code is not None:
            self.post_code = post_code
        self.town_name = town_name
        if country_sub_division is not None:
            self.country_sub_division = country_sub_division
        self.country = country

    @property
    def address_line(self):
        """Gets the address_line of this RiskDeliveryAddress.  # noqa: E501

        Information that locates and identifies a specific address, as defined by postal services, that is presented in free format text.  # noqa: E501

        :return: The address_line of this RiskDeliveryAddress.  # noqa: E501
        :rtype: list[str]
        """
        return self._address_line

    @address_line.setter
    def address_line(self, address_line):
        """Sets the address_line of this RiskDeliveryAddress.

        Information that locates and identifies a specific address, as defined by postal services, that is presented in free format text.  # noqa: E501

        :param address_line: The address_line of this RiskDeliveryAddress.  # noqa: E501
        :type: list[str]
        """

        self._address_line = address_line

    @property
    def street_name(self):
        """Gets the street_name of this RiskDeliveryAddress.  # noqa: E501

        Name of a street or thoroughfare  # noqa: E501

        :return: The street_name of this RiskDeliveryAddress.  # noqa: E501
        :rtype: str
        """
        return self._street_name

    @street_name.setter
    def street_name(self, street_name):
        """Sets the street_name of this RiskDeliveryAddress.

        Name of a street or thoroughfare  # noqa: E501

        :param street_name: The street_name of this RiskDeliveryAddress.  # noqa: E501
        :type: str
        """
        if street_name is not None and len(street_name) > 70:
            raise ValueError("Invalid value for `street_name`, length must be less than or equal to `70`")  # noqa: E501
        if street_name is not None and len(street_name) < 1:
            raise ValueError("Invalid value for `street_name`, length must be greater than or equal to `1`")  # noqa: E501

        self._street_name = street_name

    @property
    def building_number(self):
        """Gets the building_number of this RiskDeliveryAddress.  # noqa: E501

        Number that identifies the position of a building on a street.  # noqa: E501

        :return: The building_number of this RiskDeliveryAddress.  # noqa: E501
        :rtype: str
        """
        return self._building_number

    @building_number.setter
    def building_number(self, building_number):
        """Sets the building_number of this RiskDeliveryAddress.

        Number that identifies the position of a building on a street.  # noqa: E501

        :param building_number: The building_number of this RiskDeliveryAddress.  # noqa: E501
        :type: str
        """
        if building_number is not None and len(building_number) > 16:
            raise ValueError("Invalid value for `building_number`, length must be less than or equal to `16`")  # noqa: E501
        if building_number is not None and len(building_number) < 1:
            raise ValueError("Invalid value for `building_number`, length must be greater than or equal to `1`")  # noqa: E501

        self._building_number = building_number

    @property
    def post_code(self):
        """Gets the post_code of this RiskDeliveryAddress.  # noqa: E501

        Identifier consisting of a group of letters and/or numbers that is added to a postal address to assist the sorting of mail  # noqa: E501

        :return: The post_code of this RiskDeliveryAddress.  # noqa: E501
        :rtype: str
        """
        return self._post_code

    @post_code.setter
    def post_code(self, post_code):
        """Sets the post_code of this RiskDeliveryAddress.

        Identifier consisting of a group of letters and/or numbers that is added to a postal address to assist the sorting of mail  # noqa: E501

        :param post_code: The post_code of this RiskDeliveryAddress.  # noqa: E501
        :type: str
        """
        if post_code is not None and len(post_code) > 16:
            raise ValueError("Invalid value for `post_code`, length must be less than or equal to `16`")  # noqa: E501
        if post_code is not None and len(post_code) < 1:
            raise ValueError("Invalid value for `post_code`, length must be greater than or equal to `1`")  # noqa: E501

        self._post_code = post_code

    @property
    def town_name(self):
        """Gets the town_name of this RiskDeliveryAddress.  # noqa: E501

        Name of a built-up area, with defined boundaries, and a local government.  # noqa: E501

        :return: The town_name of this RiskDeliveryAddress.  # noqa: E501
        :rtype: str
        """
        return self._town_name

    @town_name.setter
    def town_name(self, town_name):
        """Sets the town_name of this RiskDeliveryAddress.

        Name of a built-up area, with defined boundaries, and a local government.  # noqa: E501

        :param town_name: The town_name of this RiskDeliveryAddress.  # noqa: E501
        :type: str
        """
        if town_name is None:
            raise ValueError("Invalid value for `town_name`, must not be `None`")  # noqa: E501
        if town_name is not None and len(town_name) > 35:
            raise ValueError("Invalid value for `town_name`, length must be less than or equal to `35`")  # noqa: E501
        if town_name is not None and len(town_name) < 1:
            raise ValueError("Invalid value for `town_name`, length must be greater than or equal to `1`")  # noqa: E501

        self._town_name = town_name

    @property
    def country_sub_division(self):
        """Gets the country_sub_division of this RiskDeliveryAddress.  # noqa: E501

        Identifies a subdivision of a country, for instance state, region, county.  # noqa: E501

        :return: The country_sub_division of this RiskDeliveryAddress.  # noqa: E501
        :rtype: list[str]
        """
        return self._country_sub_division

    @country_sub_division.setter
    def country_sub_division(self, country_sub_division):
        """Sets the country_sub_division of this RiskDeliveryAddress.

        Identifies a subdivision of a country, for instance state, region, county.  # noqa: E501

        :param country_sub_division: The country_sub_division of this RiskDeliveryAddress.  # noqa: E501
        :type: list[str]
        """

        self._country_sub_division = country_sub_division

    @property
    def country(self):
        """Gets the country of this RiskDeliveryAddress.  # noqa: E501

        Nation with its own government, occupying a particular territory.  # noqa: E501

        :return: The country of this RiskDeliveryAddress.  # noqa: E501
        :rtype: str
        """
        return self._country

    @country.setter
    def country(self, country):
        """Sets the country of this RiskDeliveryAddress.

        Nation with its own government, occupying a particular territory.  # noqa: E501

        :param country: The country of this RiskDeliveryAddress.  # noqa: E501
        :type: str
        """
        if country is None:
            raise ValueError("Invalid value for `country`, must not be `None`")  # noqa: E501
        if country is not None and not re.search('^[A-Z]{2,2}$', country):  # noqa: E501
            raise ValueError("Invalid value for `country`, must be a follow pattern or equal to `/^[A-Z]{2,2}$/`")  # noqa: E501

        self._country = country

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RiskDeliveryAddress):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
